# Setup
title: Slade's Blo(n)g(er)
url: https://blonger.sladewatkins.com
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .github
  - .gitignore
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Slade Watkins
  url: https://twitter.com/sladewatkins
  email: slade@sladewatkins.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:

  - title: Home
    url: https://www.sladewatkins.com
  - title: Blog
    url: /
